### ISSUE TITLE
How can I do the test for the submission?

### ISSUE THREAD

**Issue by LittleFlyingSheep** [xieh97/dcase2022-audio-retrieval#1]
Hi, I am going to join this challenge.  How can I do the data preprocessing for the test result?

**Comment by xieh97** [comment]
Hi @LittleFlyingSheep,

Thank you for your interest in the language-based audio retrieval subtask!

Unfortunately, this repository does not provide functions of data preprocessing for the test results. Participants are supposed to implement related functions for their systems.

For the submission, participants should submit the output (`*.csv` file) of their audio retrieval with the evaluation data, containing 11 columns:

  1. `caption`: the query caption.
  2. `file_name_1`: file name of the audio file that is **most relevant** to the query caption in `caption`.
  3. `file_name_2`: file name of the audio file that is **2nd** most relevant to the query caption in `caption`.
  4. `file_name_3`: file name of the audio file that is **3rd** most relevant to the query caption in `caption`.
  5. `file_name_4`: file name of the audio file that is **4th** most relevant to the query caption in `caption`.
  6. `file_name_5`: file name of the audio file that is **5th** most relevant to the query caption in `caption`.
  7. `file_name_6`: file name of the audio file that is **6th** most relevant to the query caption in `caption`.
  8. `file_name_7`: file name of the audio file that is **7th** most relevant to the query caption in `caption`.
  9. `file_name_8`: file name of the audio file that is **8th** most relevant to the query caption in `caption`.
  10. `file_name_9`: file name of the audio file that is **9th** most relevant to the query caption in `caption`.
  11. `file_name_10`: file name of the audio file that is **10th** most relevant to the query caption in `caption`.

Apart from the `*.csv` file, participants should also submit:

 - metadata for their submission (`*.yaml` file), and
 - a technical report for their submission (`*.pdf` file).

More information about the submission requirements could be found in the task webpage (https://dcase.community/challenge2022/task-language-based-audio-retrieval).

Hope this helps.

Best,
xieh97

**Comment by LittleFlyingSheep** [comment]
收到
